### testing api call

## User

### GET User
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5AZy5jb20iLCJpYXQiOjE3OTAzMDMwMzksImV4cCI6MTc5MDMwMzA5OX0.phPbVMmM2bI1LwGKP1YhkVxFov4MmIP_QjkbTXP2NLM
### SignUp User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Nate",
    "email": "n@g.com",
    "password": "1111"
}

### Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "n@g.com",
    "password": "1111"
}

