### testing api call

## User

### GET User
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5AZy5jb20iLCJpYXQiOjE3OTAzMDMwMzksImV4cCI6MTc5MDMwMzA5OX0.phPbVMmM2bI1LwGKP1YhkVxFov4MmIP_QjkbTXP2NLM
### SignUp User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Nate",
    "email": "n@g.com",
    "password": "1111"
}

### Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "n@g.com",
    "password": "1111"
}


### Post new transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5AZy5jb20iLCJpYXQiOjE3OTEwMDMzODQsImV4cCI6MTc5MTA4OTc4NH0.JvrgiSdIr6FMmCTbnbVXj0bT6nlxcIM9CZ16eVc-6Qc

{
    "type": "Income",
  "title": "Land sell",
 "amount": "2000",
  "tdate": "2026-09-27"
}

### Get all Transaction for a user
GET http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5AZy5jb20iLCJpYXQiOjE3OTA1Njg3OTEsImV4cCI6MTc5MDY1NTE5MX0.EUjaRNdKOPASJN84L9Zk2_DcWufrhll8eDmf1Umr43U


### Delete transaction
DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5AZy5jb20iLCJpYXQiOjE3OTEwMDMzODQsImV4cCI6MTc5MTA4OTc4NH0.JvrgiSdIr6FMmCTbnbVXj0bT6nlxcIM9CZ16eVc-6Qc

["6ac08b296fa3ea2968433344", "6abe6890bd7a06685a93b12e"]
